spring:
  config:
    activate:
      on-profile: prod

  application:
    name: e-tutor
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
    database: postgresql

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs

---

spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:etutor
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
    database: h2

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
#        session: TRACE
quiz:
  generator:
    url: "http://localhost:8000/"
jwt:
  secret: "ba67831e2342e9c768c0b8954a33f28a9f156babbb80e80cc0f1614fcd07d4ec3f4fbabc636ee5f1777af1ca219372a12c3ec4df4b8715202fdd82a73badc4423060a0608eb8c8d8c7a77d7361c79dc32601e6ce33d25e2be0f7dcbeca2120194ec47ddbbbfe04b0fa96a0425e31d3f5ea385b533fcf9edcec78d91f50cc2495a4d39f233fb39e7cc660096c271b364b53f0db356d748420b0596ef23ccffa5d27822224c2156a9290d6ac12b09aec2c5ebfe793b370fca99b4f0f87bd690fd3fbbe637d0f400ee383ecf5f910fadb03be01a3ebb0967064f6e7fb71fd31f9d4eb1de13cc01a6e017307a7db5da04a535fcf8d9de9b58ba3f79fee98a8938ba1"
  expiration: 3600000