spring:
  config:
    activate:
      on-profile: prod
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  application:
    name: e-tutor
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
    database: postgresql

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs

date-time:
  format: "dd-MM-yyyy HH:mm"

jwt:
  secret: "ba67831e2342e9c768c0b8954a33f28a9f156babbb80e80cc0f1614fcd07d4ec3f4fbabc636ee5f1777af1ca219372a12c3ec4df4b8715202fdd82a73badc4423060a0608eb8c8d8c7a77d7361c79dc32601e6ce33d25e2be0f7dcbeca2120194ec47ddbbbfe04b0fa96a0425e31d3f5ea385b533fcf9edcec78d91f50cc2495a4d39f233fb39e7cc660096c271b364b53f0db356d748420b0596ef23ccffa5d27822224c2156a9290d6ac12b09aec2c5ebfe793b370fca99b4f0f87bd690fd3fbbe637d0f400ee383ecf5f910fadb03be01a3ebb0967064f6e7fb71fd31f9d4eb1de13cc01a6e017307a7db5da04a535fcf8d9de9b58ba3f79fee98a8938ba1"
  expiration: 3600000

app:
  front-end:
    url: http://localhost:5173

server:
  port: ${PORT:8080}